version: "3"

services:
  ros:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: ros_noetic

    devices:
      - /dev:/dev
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0


    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/ros_ws
    working_dir: /ros_ws

    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
