// Generated by gencpp from file serial_stm32/verter.msg
// DO NOT EDIT!


#ifndef SERIAL_STM32_MESSAGE_VERTER_H
#define SERIAL_STM32_MESSAGE_VERTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_stm32
{
template <class ContainerAllocator>
struct verter_
{
  typedef verter_<ContainerAllocator> Type;

  verter_()
    : x(0)
    , y(0)  {
    }
  verter_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int8_t _x_type;
  _x_type x;

   typedef int8_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::serial_stm32::verter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_stm32::verter_<ContainerAllocator> const> ConstPtr;

}; // struct verter_

typedef ::serial_stm32::verter_<std::allocator<void> > verter;

typedef boost::shared_ptr< ::serial_stm32::verter > verterPtr;
typedef boost::shared_ptr< ::serial_stm32::verter const> verterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_stm32::verter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_stm32::verter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_stm32::verter_<ContainerAllocator1> & lhs, const ::serial_stm32::verter_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_stm32::verter_<ContainerAllocator1> & lhs, const ::serial_stm32::verter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_stm32

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_stm32::verter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_stm32::verter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_stm32::verter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_stm32::verter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_stm32::verter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_stm32::verter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_stm32::verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a20b9d8cfb71fa36c504f7f2d8fb5dc";
  }

  static const char* value(const ::serial_stm32::verter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a20b9d8cfb71fa3ULL;
  static const uint64_t static_value2 = 0x6c504f7f2d8fb5dcULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_stm32::verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_stm32/verter";
  }

  static const char* value(const ::serial_stm32::verter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_stm32::verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 x\n"
"int8 y\n"
;
  }

  static const char* value(const ::serial_stm32::verter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_stm32::verter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct verter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_stm32::verter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_stm32::verter_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_STM32_MESSAGE_VERTER_H
