// Generated by gencpp from file bot_move/Verter.msg
// DO NOT EDIT!


#ifndef BOT_MOVE_MESSAGE_VERTER_H
#define BOT_MOVE_MESSAGE_VERTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_move
{
template <class ContainerAllocator>
struct Verter_
{
  typedef Verter_<ContainerAllocator> Type;

  Verter_()
    : x(0.0)
    , y(0.0)  {
    }
  Verter_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::bot_move::Verter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_move::Verter_<ContainerAllocator> const> ConstPtr;

}; // struct Verter_

typedef ::bot_move::Verter_<std::allocator<void> > Verter;

typedef boost::shared_ptr< ::bot_move::Verter > VerterPtr;
typedef boost::shared_ptr< ::bot_move::Verter const> VerterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_move::Verter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_move::Verter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bot_move::Verter_<ContainerAllocator1> & lhs, const ::bot_move::Verter_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bot_move::Verter_<ContainerAllocator1> & lhs, const ::bot_move::Verter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bot_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bot_move::Verter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_move::Verter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_move::Verter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_move::Verter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_move::Verter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_move::Verter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_move::Verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::bot_move::Verter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_move::Verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_move/Verter";
  }

  static const char* value(const ::bot_move::Verter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_move::Verter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::bot_move::Verter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_move::Verter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Verter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_move::Verter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_move::Verter_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_MOVE_MESSAGE_VERTER_H
