base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0

  acc_lim_x: 1.0
  acc_lim_theta: 2.0

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2